# Generated by Django 3.2.22 on 2023-11-01 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
        ('polls', '0003_poll_vote_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='shoe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('user', 'poll', 'shoe')},
        ),
    ]
