# Generated by Django 3.2.22 on 2023-11-05 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20231101_1319'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RunningShoe',
        ),
    ]
