# Generated by Django 3.2.22 on 2023-11-02 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='https://res.cloudinary.com/dnkoqrvie/image/upload/v1697040192/media/images/banner_rzae6b.jpg', upload_to='images/'),
        ),
    ]
