# Generated by Django 3.2.22 on 2023-10-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../blank-profile-picture-973460_1280_fxozyw', upload_to='images/'),
        ),
    ]
