# Generated by Django 3.2.22 on 2023-11-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='https://res.cloudinary.com/dnkoqrvie/image/upload/v1693398098/blank-profile-picture.webp', upload_to='images/'),
        ),
    ]
