# Generated by Django 3.2.22 on 2023-11-02 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='https://res.cloudinary.com/dnkoqrvie/image/upload/v1698962923/media/images/blank-profile-image_ztb3iv.jpg', upload_to='images/'),
        ),
    ]
